version: '3.8'
services:
  auth-db:
    image: postgres:17
    container_name: auth-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data  # to prevent delete all data

volumes:
  auth_db_data: