version: '3.8'
services:
  auth-db:
    image: postgres:17
    container_name: auth-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data  # to prevent delete all data


  mongo-db:
    image: mongo:6.0
    container_name: mongo-db-container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 1234
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-container
    restart: always

    platform: linux/amd64

    environment:
      - REDIS_HOSTS=local:redis:6379:0:1234
    ports:
      - "8001:8081"
    depends_on:
      - redis

volumes:
  auth_db_data:
  mongo_data:
  redis_data:
